### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by muhammedfurkan** [microsoft/vscode-isort#134]
The extension doesn't work in the python 3.11 version. It gives an error message. Please add python latest version support.

![image](https://user-images.githubusercontent.com/9547040/198819193-c19f3f75-76fe-4a5b-9be9-857c57b416a8.png)

**Comment by karthiknadig** [comment]
@muhammedfurkan This is fixed in the pre-release version. Please install pre-release version. The stable version will be release next week.
![image](https://user-images.githubusercontent.com/3840081/198819514-7fa3e6c0-e863-4d7a-9817-9b2fffd59819.png)

**Comment by muhammedfurkan** [comment]
It's already a pre-release version, but still the same. Same issue with the black formatter.

**Comment by karthiknadig** [comment]
@muhammedfurkan You have `isort` and `black` both in pre-release version. Also, please share the Logs from Output > Isort or Output > black Formatter . If the logs say the issue is due to an error in `pydantic` then that is fixed in the pre-release. And you will need  pre-release  of  python extension, isort extension and black extension.

**Comment by muhammedfurkan** [comment]
# isort Formatter

`Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\tool\server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x000002672BBF0400>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:15] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\tool\server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000014978040400>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:16] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\tool\server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000025A0E0B0400>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:17] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\tool\server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000022675E80400>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:18] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\tool\server.py", line 41, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.isort-2022.3.12771042\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000022297AB0400>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Error - 10:31:18] Connection to server got closed. Server will not be restarted.
`

---------------------------------
# Black Formatter


`Name: Black Formatter
Module: black
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\tool\server.py", line 40, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x000002B8F1D50AE0>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:15] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\tool\server.py", line 40, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000018F9DB24A40>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:16] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\tool\server.py", line 40, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000016ACEA24A40>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:17] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\tool\server.py", line 40, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000020374C74A40>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 10:31:17] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\tool\server.py", line 40, in <module>
    from pygls import lsp, protocol, server, uris, workspace
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\__init__.py", line 6, in <module>
    from pygls.lsp.types.general_messages import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\general_messages.py", line 35, in <module>
    from pygls.lsp.types.language_features import (CallHierarchyClientCapabilities,
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\__init__.py", line 2, in <module>
    from pygls.lsp.types.language_features.call_hierarchy import *
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pygls\lsp\types\language_features\call_hierarchy.py", line 70, in <module>
    class CallHierarchyIncomingCall(Model):
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\M.Furkan\.vscode\extensions\ms-python.black-formatter-2022.4.0\bundled\libs\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\M.Furkan\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x000002C0D4C04A40>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
[Error - 10:31:18] Connection to server got closed. Server will not be restarted.
`
